name: CI/CD to GitHub Pages

on:
  push:
      branches: [master]

jobs:
  build:
        name: Build 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: List files (simulate build)
              run: ls -l 
          
  test:
      name: Test 
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Validate HTML (simulate test)
          run: echo "Test stage passed!"

  deploy:
        name: Deploy 
        runs-on: ubuntu-latest
        needs: test
        permissions: 
                contents: write
                pages: write
                id-token: write
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v4
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: .